# Generated by Django 6.0.4 on 2026-05-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_event_book_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="books/covers/", verbose_name="Обложка"
            ),
        ),
    ]
