# Generated by Django 6.0.4 on 2026-05-31 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_genre_parent"),
    ]

    operations = []
